window.TRIP_META = {
  title: "Qué ver en Ámsterdam en 3 días",
  subtitle: "Viaje familiar: llegada vie 10 jul 2026, regreso lun 13 jul 2026 (familias con niños/as)",
  warning: "Horarios y entradas cambian; verifica siempre en la web oficial."
};

window.DAY_ORDER = ["day1", "day2", "day3"];
window.SEGMENT_ORDER = ["morning", "afternoon", "night"];

window.DAY_LABELS = {
  day1: "10 de julio",
  day2: "11 de julio",
  day3: "12 de julio"
};

window.SEGMENT_LABELS = {
  morning: "Mañana",
  afternoon: "Tarde",
  night: "Noche"
};

window.HOTEL_REFERENCE = {
  id: "hotel-best-western-amsterdam",
  nombre: "Best Western Amsterdam",
  direccion: "Voorburgstraat 250, Amsterdam 1059 VD",
  barrio: "Amsterdam Nieuw-West",
  telefono_hotel: "+31 85 2733568",
  telefono_reservas: "+1 (800) 780-7234",
  checkin: "15:00 CEST",
  checkout: "11:00 CEST",
  lat: 52.3506,
  lng: 4.8395
};

window.TRAVEL_LOGISTICS = {
  hotel: window.HOTEL_REFERENCE,
  flights: [
    {
      id: "outbound-eju7890",
      ruta: "Málaga -> Ámsterdam",
      numero: "EJU7890",
      salida: "Viernes 10 julio 2026, 11:20",
      llegada: "Viernes 10 julio 2026, 14:25",
      equipaje_apertura: "09:20",
      equipaje_cierre: "10:40"
    },
    {
      id: "inbound-hv6227",
      ruta: "Ámsterdam (Schiphol) -> Málaga",
      numero: "HV6227",
      salida: "Lunes 13 julio 2026, 20:15",
      llegada: "Lunes 13 julio 2026, 23:15",
      nota: "Recomendado salir del hotel hacia Schiphol sobre las 17:00-17:30."
    }
  ]
};

window.DEPARTURE_DAY_PLAN = {
  label: "13 de julio (salida)",
  subtitle: "Mini-vista operativa no editable",
  items: [
    {
      hora: "08:30",
      titulo: "Desayuno y cierre de maletas",
      detalle: "Revisar documentos, pasaportes, cargadores y objetos de valor."
    },
    {
      hora: "11:00",
      titulo: "Check-out en Best Western Amsterdam",
      detalle: "Dejar equipaje en consigna del hotel para aprovechar el día."
    },
    {
      hora: "12:00-16:30",
      titulo: "Bloque flexible de despedida",
      detalle: "Plan A: paseo suave + comida. Plan B: opción indoor cercana."
    },
    {
      hora: "17:00-17:30",
      titulo: "Salida al aeropuerto Schiphol",
      detalle: "Recomendado para llegar con margen al vuelo HV6227 (20:15)."
    },
    {
      hora: "20:15",
      titulo: "Vuelo de regreso HV6227",
      detalle: "Salida Ámsterdam (Schiphol) -> llegada Málaga 23:15."
    }
  ]
};

window.POIS = [
  {
    id: "hotel-best-western-amsterdam",
    nombre: "Best Western Amsterdam (Hotel base)",
    descripcion_corta: "Hotel de referencia para iniciar/cerrar cada jornada.",
    categoria: "hotel",
    tags: ["hotel", "base", "check-in", "referencia"],
    barrio: "Amsterdam Nieuw-West",
    direccion: "Voorburgstraat 250, Amsterdam 1059 VD",
    enlace_oficial: "https://www.bestwestern.com/",
    reserva_requerida: true,
    notas_reserva: "Check-in 15:00 / Check-out 11:00 (CEST).",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 30,
    coste_nivel: "€€",
    edad_recomendada: "Todas",
    lat: 52.3506,
    lng: 4.8395
  },
  {
    id: "schiphol-airport",
    nombre: "Amsterdam Schiphol Airport",
    descripcion_corta: "Aeropuerto principal: llegadas y salida del viaje.",
    categoria: "transporte",
    tags: ["aeropuerto", "vuelo", "traslado", "schiphol"],
    barrio: "Schiphol",
    direccion: "Aankomstpassage 1, 1118 AX Schiphol",
    enlace_oficial: "https://www.schiphol.nl",
    reserva_requerida: false,
    notas_reserva: "Para el vuelo de vuelta, salir del hotel entre 17:00 y 17:30.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 60,
    coste_nivel: "€",
    edad_recomendada: "Todas",
    lat: 52.3105,
    lng: 4.7683
  },
  {
    id: "nemo-science-museum",
    nombre: "NEMO Science Museum",
    descripcion_corta: "Museo de ciencia interactivo con muchas actividades practicas para teens.",
    categoria: "ciencia",
    tags: ["ciencia", "familia", "experimentos", "tech"],
    barrio: "Oosterdok",
    direccion: "Oosterdok 2, 1011 VX Amsterdam",
    enlace_oficial: "https://www.nemosciencemuseum.nl",
    reserva_requerida: true,
    notas_reserva: "Mejor reservar franja horaria con antelacion.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 150,
    coste_nivel: "€€",
    edad_recomendada: "10-18",
    lat: 52.3742,
    lng: 4.9122
  },
  {
    id: "nemo-rooftop",
    nombre: "NEMO Rooftop",
    descripcion_corta: "Terraza del NEMO con vistas y juegos de agua en temporada.",
    categoria: "mirador",
    tags: ["mirador", "vistas", "foto", "rooftop"],
    barrio: "Oosterdok",
    direccion: "Oosterdok 2, 1011 VX Amsterdam",
    enlace_oficial: "https://www.nemosciencemuseum.nl/en/visit/roof-square/",
    reserva_requerida: false,
    notas_reserva: "Acceso sujeto a horario y clima.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 45,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3743,
    lng: 4.9125
  },
  {
    id: "maritime-museum",
    nombre: "Het Scheepvaartmuseum",
    descripcion_corta: "Museo maritimo con barco historico y exposiciones interactivas.",
    categoria: "museo",
    tags: ["museo", "barco", "historia", "indoor"],
    barrio: "Kattenburg",
    direccion: "Kattenburgerplein 1, 1018 KK Amsterdam",
    enlace_oficial: "https://www.hetscheepvaartmuseum.com",
    reserva_requerida: true,
    notas_reserva: "Reserva recomendada en fines de semana.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 120,
    coste_nivel: "€€",
    edad_recomendada: "10-18",
    lat: 52.3719,
    lng: 4.9147
  },
  {
    id: "artis-zoo",
    nombre: "ARTIS Zoo",
    descripcion_corta: "Zoo historico con acuario y zonas verdes para grupo grande.",
    categoria: "zoo",
    tags: ["animales", "familia", "parque", "outdoor"],
    barrio: "Plantage",
    direccion: "Plantage Kerklaan 38-40, 1018 CZ Amsterdam",
    enlace_oficial: "https://www.artis.nl",
    reserva_requerida: true,
    notas_reserva: "Compra anticipada recomendada.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 150,
    coste_nivel: "€€",
    edad_recomendada: "8-18",
    lat: 52.366,
    lng: 4.9167
  },
  {
    id: "tropenmuseum",
    nombre: "Tropenmuseum",
    descripcion_corta: "Museo cultural con exposiciones globales y actividades familiares.",
    categoria: "museo",
    tags: ["museo", "cultura", "lluvia", "indoor"],
    barrio: "Oost",
    direccion: "Linnaeusstraat 2, 1092 CK Amsterdam",
    enlace_oficial: "https://www.tropenmuseum.nl",
    reserva_requerida: false,
    notas_reserva: "Revisar talleres especiales para adolescentes.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 105,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3638,
    lng: 4.9229
  },
  {
    id: "dam-square",
    nombre: "Dam Square",
    descripcion_corta: "Plaza central con ambiente urbano y punto de encuentro facil.",
    categoria: "paseo",
    tags: ["centro", "plaza", "foto", "meeting point"],
    barrio: "Centrum",
    direccion: "Dam, 1012 JS Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Sin reserva.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 35,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3731,
    lng: 4.8922
  },
  {
    id: "anne-frank-house",
    nombre: "Anne Frank House",
    descripcion_corta: "Museo historico muy solicitado, visita de alto valor educativo.",
    categoria: "museo",
    tags: ["historia", "educativo", "indoor", "reserva"],
    barrio: "Jordaan",
    direccion: "Westermarkt 20, 1016 GV Amsterdam",
    enlace_oficial: "https://www.annefrank.org",
    reserva_requerida: true,
    notas_reserva: "Entradas online con mucha antelacion.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 75,
    coste_nivel: "€€",
    edad_recomendada: "12+",
    lat: 52.3752,
    lng: 4.8839
  },
  {
    id: "nine-straatjes",
    nombre: "De 9 Straatjes",
    descripcion_corta: "Calles pintorescas con tiendas, cafes y canales.",
    categoria: "paseo",
    tags: ["canales", "compras", "foto", "walking"],
    barrio: "Grachtengordel",
    direccion: "Negen Straatjes, Amsterdam",
    enlace_oficial: "https://de9straatjes.nl",
    reserva_requerida: false,
    notas_reserva: "Ideal para paseo flexible.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 90,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3707,
    lng: 4.8867
  },
  {
    id: "jordaan-canal-walk",
    nombre: "Paseo Jordaan + Canales",
    descripcion_corta: "Ruta a pie por uno de los barrios mas bonitos de la ciudad.",
    categoria: "paseo",
    tags: ["jordaan", "canales", "walking", "outdoor"],
    barrio: "Jordaan",
    direccion: "Jordaan, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Sin reserva, ideal con buffer de tiempo.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 95,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3745,
    lng: 4.8791
  },
  {
    id: "canal-cruise-central",
    nombre: "Canal Cruise (salida central)",
    descripcion_corta: "Paseo en barco por canales; buen plan para descansar piernas.",
    categoria: "barco",
    tags: ["barco", "canales", "familia", "lluvia"],
    barrio: "Centrum",
    direccion: "Prins Hendrikkade, Amsterdam",
    enlace_oficial: "https://www.lovers.nl",
    reserva_requerida: true,
    notas_reserva: "Comparar horarios y reservar online.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 75,
    coste_nivel: "€€",
    edad_recomendada: "8-18",
    lat: 52.3769,
    lng: 4.9008
  },
  {
    id: "rijksmuseum",
    nombre: "Rijksmuseum",
    descripcion_corta: "Museo iconico de arte e historia neerlandesa.",
    categoria: "museo",
    tags: ["arte", "historia", "museumplein", "indoor"],
    barrio: "Museumkwartier",
    direccion: "Museumstraat 1, 1071 XX Amsterdam",
    enlace_oficial: "https://www.rijksmuseum.nl",
    reserva_requerida: true,
    notas_reserva: "Reserva franja; llegar 15 min antes.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 135,
    coste_nivel: "€€",
    edad_recomendada: "12+",
    lat: 52.36,
    lng: 4.8852
  },
  {
    id: "van-gogh-museum",
    nombre: "Van Gogh Museum",
    descripcion_corta: "Coleccion de Van Gogh muy popular y apta para adolescentes.",
    categoria: "museo",
    tags: ["arte", "indoor", "museumplein", "reserva"],
    barrio: "Museumkwartier",
    direccion: "Museumplein 6, 1071 DJ Amsterdam",
    enlace_oficial: "https://www.vangoghmuseum.nl",
    reserva_requerida: true,
    notas_reserva: "Entradas por hora, cupos limitados.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 120,
    coste_nivel: "€€",
    edad_recomendada: "12+",
    lat: 52.3584,
    lng: 4.8811
  },
  {
    id: "moco-museum",
    nombre: "Moco Museum",
    descripcion_corta: "Arte moderno y street art (Banksy y mas) en formato agil.",
    categoria: "museo",
    tags: ["arte", "street art", "teen", "indoor"],
    barrio: "Museumkwartier",
    direccion: "Honthorststraat 20, 1071 DE Amsterdam",
    enlace_oficial: "https://mocomuseum.com",
    reserva_requerida: true,
    notas_reserva: "Reserva recomendada para evitar colas.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 75,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3581,
    lng: 4.8819
  },
  {
    id: "museumplein",
    nombre: "Museumplein",
    descripcion_corta: "Gran explanada para descansar y reunirse entre museos.",
    categoria: "parque",
    tags: ["museumplein", "descanso", "outdoor", "meeting"],
    barrio: "Museumkwartier",
    direccion: "Museumplein, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Sin reserva.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 40,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3579,
    lng: 4.8812
  },
  {
    id: "vondelpark",
    nombre: "Vondelpark",
    descripcion_corta: "Parque grande para caminar, bici y pausa de picnic.",
    categoria: "parque",
    tags: ["parque", "bici", "picnic", "outdoor"],
    barrio: "Amsterdam-Zuid",
    direccion: "Vondelpark, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Ideal con buen clima.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 80,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.357,
    lng: 4.8686
  },
  {
    id: "foodhallen",
    nombre: "Foodhallen",
    descripcion_corta: "Food hall cubierto con muchas opciones para grupos grandes.",
    categoria: "mercado",
    tags: ["comida", "indoor", "grupo", "de hallen"],
    barrio: "Oud-West",
    direccion: "Bellamyplein 51, 1053 AT Amsterdam",
    enlace_oficial: "https://foodhallen.nl",
    reserva_requerida: false,
    notas_reserva: "En hora punta conviene llegar temprano.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 90,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3662,
    lng: 4.8681
  },
  {
    id: "albert-cuyp-market",
    nombre: "Albert Cuyp Market",
    descripcion_corta: "Mercado callejero famoso en De Pijp para snacks y souvenirs.",
    categoria: "mercado",
    tags: ["mercado", "street food", "outdoor", "de pijp"],
    barrio: "De Pijp",
    direccion: "Albert Cuypstraat, Amsterdam",
    enlace_oficial: "https://www.albertcuypmarkt.nl",
    reserva_requerida: false,
    notas_reserva: "Cierra mas temprano que otras zonas.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 75,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3541,
    lng: 4.8914
  },
  {
    id: "de-pijp-stroll",
    nombre: "Paseo por De Pijp",
    descripcion_corta: "Barrio joven con cafes y ambiente local.",
    categoria: "paseo",
    tags: ["barrio", "walking", "cafes", "teen"],
    barrio: "De Pijp",
    direccion: "De Pijp, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Buena zona para cena flexible.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 65,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3546,
    lng: 4.8898
  },
  {
    id: "adam-lookout",
    nombre: "A'DAM LOOKOUT",
    descripcion_corta: "Mirador 360 en Noord con columpio sobre el skyline.",
    categoria: "mirador",
    tags: ["mirador", "noord", "foto", "adrenalina"],
    barrio: "Amsterdam-Noord",
    direccion: "Overhoeksplein 5, 1031 KS Amsterdam",
    enlace_oficial: "https://www.adamlookout.com",
    reserva_requerida: true,
    notas_reserva: "Recomendable reservar horario de subida.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 90,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3841,
    lng: 4.9012
  },
  {
    id: "this-is-holland",
    nombre: "THIS IS HOLLAND",
    descripcion_corta: "Simulador de vuelo 5D por paisajes neerlandeses.",
    categoria: "experiencia",
    tags: ["simulador", "indoor", "noord", "lluvia"],
    barrio: "Amsterdam-Noord",
    direccion: "Overhoeksplein 51, 1031 KS Amsterdam",
    enlace_oficial: "https://www.thisisholland.com",
    reserva_requerida: true,
    notas_reserva: "Comprar tickets online para evitar espera.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 75,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3845,
    lng: 4.9005
  },
  {
    id: "eye-filmmuseum",
    nombre: "Eye Filmmuseum",
    descripcion_corta: "Museo de cine con edificio iconico y vistas al IJ.",
    categoria: "museo",
    tags: ["cine", "noord", "arquitectura", "indoor"],
    barrio: "Amsterdam-Noord",
    direccion: "IJpromenade 1, 1031 KT Amsterdam",
    enlace_oficial: "https://www.eyefilm.nl",
    reserva_requerida: false,
    notas_reserva: "Revisar programacion de proyecciones.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 90,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3834,
    lng: 4.9002
  },
  {
    id: "straat-museum",
    nombre: "STRAAT Museum",
    descripcion_corta: "Gran museo de street art dentro de un antiguo astillero.",
    categoria: "street art",
    tags: ["street art", "graffiti", "noord", "indoor"],
    barrio: "NDSM",
    direccion: "NDSM-Plein 1, 1033 WC Amsterdam",
    enlace_oficial: "https://straatmuseum.com",
    reserva_requerida: true,
    notas_reserva: "Reserva recomendada para grupos.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 100,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.4012,
    lng: 4.8942
  },
  {
    id: "ndsm-wharf",
    nombre: "NDSM Wharf",
    descripcion_corta: "Zona creativa al aire libre con arte urbano y espacios amplios.",
    categoria: "street art",
    tags: ["noord", "outdoor", "street art", "creative"],
    barrio: "NDSM",
    direccion: "NDSM-Plein, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Sin reserva, pero revisar eventos puntuales.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 80,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.401,
    lng: 4.8948
  },
  {
    id: "ferry-noord",
    nombre: "Ferry gratis a Noord",
    descripcion_corta: "Cruce gratuito desde Centraal hacia Buiksloterweg.",
    categoria: "transporte",
    tags: ["ferry", "gratis", "noord", "familia"],
    barrio: "IJ",
    direccion: "Detras de Amsterdam Centraal",
    enlace_oficial: "https://www.gvb.nl/en/ferry",
    reserva_requerida: false,
    notas_reserva: "Sale con alta frecuencia.",
    indoor: false,
    apto_lluvia: true,
    duracion_min: 20,
    coste_nivel: "€",
    edad_recomendada: "Todas",
    lat: 52.3792,
    lng: 4.9003
  },
  {
    id: "amsterdam-central-station",
    nombre: "Amsterdam Centraal",
    descripcion_corta: "Nodo principal para tren, tranvia, metro y punto de reunion.",
    categoria: "transporte",
    tags: ["estacion", "meeting point", "tranvia", "metro"],
    barrio: "Centrum",
    direccion: "Stationsplein, 1012 AB Amsterdam",
    enlace_oficial: "https://www.ns.nl",
    reserva_requerida: false,
    notas_reserva: "Usar como punto base para reagrupar familias.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 30,
    coste_nivel: "€",
    edad_recomendada: "Todas",
    lat: 52.3791,
    lng: 4.8994
  },
  {
    id: "rembrandtplein",
    nombre: "Rembrandtplein",
    descripcion_corta: "Zona animada para cena y paseo nocturno temprano.",
    categoria: "paseo",
    tags: ["noche", "plaza", "restaurantes", "centro"],
    barrio: "Centrum",
    direccion: "Rembrandtplein, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Elegir restaurantes con reserva para grupo grande.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 70,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3669,
    lng: 4.8965
  },
  {
    id: "amaze-amsterdam",
    nombre: "AMAZE Amsterdam",
    descripcion_corta: "Experiencia inmersiva de luz y sonido, ideal en lluvia.",
    categoria: "experiencia",
    tags: ["inmersivo", "indoor", "teen", "lluvia"],
    barrio: "Westpoort",
    direccion: "Elementenstraat 25, 1014 AR Amsterdam",
    enlace_oficial: "https://amaze-amsterdam.nl",
    reserva_requerida: true,
    notas_reserva: "Mejor comprar entrada anticipada.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 75,
    coste_nivel: "€€",
    edad_recomendada: "12+",
    lat: 52.3952,
    lng: 4.845
  },
  {
    id: "amsterdamse-bos",
    nombre: "Amsterdamse Bos",
    descripcion_corta: "Area verde enorme para actividades al aire libre y picnic.",
    categoria: "parque",
    tags: ["parque", "naturaleza", "outdoor", "familia"],
    barrio: "Amstelveen",
    direccion: "Amsterdamse Bos, Amstelveen",
    enlace_oficial: "https://www.amsterdamsebos.nl",
    reserva_requerida: false,
    notas_reserva: "Plan flexible, mejor con buen clima.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 120,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3221,
    lng: 4.8365
  },
  {
    id: "westerpark",
    nombre: "Westerpark",
    descripcion_corta: "Parque urbano con zonas culturales y cafes cercanos.",
    categoria: "parque",
    tags: ["parque", "relax", "outdoor", "west"],
    barrio: "Westerpark",
    direccion: "Westerpark, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Buena parada entre actividades del oeste.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 60,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3874,
    lng: 4.8696
  },
  {
    id: "heineken-experience",
    nombre: "Heineken Experience",
    descripcion_corta: "Tour interactivo de marca; considerar edad minima segun normas.",
    categoria: "experiencia",
    tags: ["indoor", "de pijp", "tour", "branding"],
    barrio: "De Pijp",
    direccion: "Stadhouderskade 78, 1072 AE Amsterdam",
    enlace_oficial: "https://www.heinekenexperience.com",
    reserva_requerida: true,
    notas_reserva: "Revisar restricciones de edad antes de reservar.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 90,
    coste_nivel: "€€",
    edad_recomendada: "16+",
    lat: 52.3579,
    lng: 4.8916
  },
  {
    id: "oosterpark",
    nombre: "Oosterpark",
    descripcion_corta: "Parque agradable en el este para descanso y regroup.",
    categoria: "parque",
    tags: ["parque", "relax", "outdoor", "oost"],
    barrio: "Oost",
    direccion: "Oosterpark, Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Buena opcion corta antes de cenar.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 45,
    coste_nivel: "€",
    edad_recomendada: "12-18",
    lat: 52.3601,
    lng: 4.9207
  },
  {
    id: "begijnhof",
    nombre: "Begijnhof",
    descripcion_corta: "Patio historico tranquilo en pleno centro.",
    categoria: "historia",
    tags: ["historia", "centro", "walking", "quiet"],
    barrio: "Centrum",
    direccion: "Begijnhof 1, 1012 WS Amsterdam",
    enlace_oficial: "",
    reserva_requerida: false,
    notas_reserva: "Respetar silencio en la zona.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 35,
    coste_nivel: "€",
    edad_recomendada: "12+",
    lat: 52.369,
    lng: 4.8909
  },
  {
    id: "a-mazeing-noord-cafe",
    nombre: "Pllek y entorno NDSM",
    descripcion_corta: "Zona de comida informal junto al agua en Noord.",
    categoria: "mercado",
    tags: ["comida", "noord", "waterfront", "grupo"],
    barrio: "NDSM",
    direccion: "TT Neveritaweg 59, 1033 WB Amsterdam",
    enlace_oficial: "https://pllek.nl",
    reserva_requerida: false,
    notas_reserva: "Ir temprano para grupos grandes.",
    indoor: false,
    apto_lluvia: false,
    duracion_min: 80,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.4019,
    lng: 4.8874
  },
  {
    id: "nxt-museum",
    nombre: "NXT Museum",
    descripcion_corta: "Arte digital inmersivo en Noord.",
    categoria: "museo",
    tags: ["digital", "indoor", "teen", "noord"],
    barrio: "Amsterdam-Noord",
    direccion: "Asterweg 22, 1031 HP Amsterdam",
    enlace_oficial: "https://nxtmuseum.com",
    reserva_requerida: true,
    notas_reserva: "Comprar ticket online para horario concreto.",
    indoor: true,
    apto_lluvia: true,
    duracion_min: 80,
    coste_nivel: "€€",
    edad_recomendada: "12-18",
    lat: 52.3928,
    lng: 4.9068
  }
];

window.DEFAULT_ITINERARY = {
  day1: {
    morning: [
      { entryId: "d1m1", planA: "schiphol-airport", planB: "schiphol-airport" },
      { entryId: "d1m2", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" }
    ],
    afternoon: [
      { entryId: "d1a1", planA: "vondelpark", planB: "rijksmuseum" },
      { entryId: "d1a2", planA: "foodhallen", planB: "moco-museum" },
      { entryId: "d1a3", planA: "museumplein", planB: "van-gogh-museum" }
    ],
    night: [
      { entryId: "d1n1", planA: "de-pijp-stroll", planB: "foodhallen" },
      { entryId: "d1n2", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" }
    ]
  },
  day2: {
    morning: [
      { entryId: "d2m1", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" },
      { entryId: "d2m2", planA: "ferry-noord", planB: "eye-filmmuseum" },
      { entryId: "d2m3", planA: "adam-lookout", planB: "this-is-holland" },
      { entryId: "d2m4", planA: "ndsm-wharf", planB: "straat-museum" }
    ],
    afternoon: [
      { entryId: "d2a1", planA: "straat-museum", planB: "nxt-museum" },
      { entryId: "d2a2", planA: "a-mazeing-noord-cafe", planB: "eye-filmmuseum" },
      { entryId: "d2a3", planA: "westerpark", planB: "amaze-amsterdam" }
    ],
    night: [
      { entryId: "d2n1", planA: "canal-cruise-central", planB: "foodhallen" },
      { entryId: "d2n2", planA: "rembrandtplein", planB: "amaze-amsterdam" },
      { entryId: "d2n3", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" }
    ]
  },
  day3: {
    morning: [
      { entryId: "d3m1", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" },
      { entryId: "d3m2", planA: "anne-frank-house", planB: "maritime-museum" },
      { entryId: "d3m3", planA: "nine-straatjes", planB: "rijksmuseum" }
    ],
    afternoon: [
      { entryId: "d3a1", planA: "albert-cuyp-market", planB: "tropenmuseum" },
      { entryId: "d3a2", planA: "artis-zoo", planB: "nemo-science-museum" },
      { entryId: "d3a3", planA: "oosterpark", planB: "maritime-museum" }
    ],
    night: [
      { entryId: "d3n1", planA: "canal-cruise-central", planB: "eye-filmmuseum" },
      { entryId: "d3n2", planA: "hotel-best-western-amsterdam", planB: "hotel-best-western-amsterdam" }
    ]
  }
};

window.CHECKLIST_ITEMS = [
  { id: "chk-outbound-bagdrop", grupo: "vuelos", texto: "10/07: facturar equipaje entre 09:20 y 10:40 para EJU7890." },
  { id: "chk-outbound-arrival", grupo: "vuelos", texto: "10/07 llegada 14:25 a Schiphol, luego traslado al hotel." },
  { id: "chk-return-transfer", grupo: "vuelos", texto: "13/07 salir del hotel 17:00-17:30 para vuelo HV6227 (20:15)." },
  { id: "chk-return-checkout", grupo: "vuelos", texto: "Check-out hotel a las 11:00 CEST; dejar maletas en consigna." },
  { id: "chk-ov-card", grupo: "transporte", texto: "Comprar o activar OVpay / tarjeta para tranvía y metro." },
  { id: "chk-ferry", grupo: "transporte", texto: "Recordar ferry gratis a Noord desde Centraal." },
  { id: "chk-bike-rules", grupo: "transporte", texto: "Repasar reglas de carril bici para todo el grupo." },
  { id: "chk-meeting-point", grupo: "grupo", texto: "Definir punto de encuentro fijo por cada franja del dia." },
  { id: "chk-buffer", grupo: "grupo", texto: "Añadir buffer de 15-20 min entre actividades para 4 familias." },
  { id: "chk-headcount", grupo: "grupo", texto: "Hacer recuento rapido antes de moveros de barrio." },
  { id: "chk-bookings", grupo: "reservas", texto: "Revisar reservas de museos y experiencias 24h antes." },
  { id: "chk-food", grupo: "reservas", texto: "Tener opción de comida rápida para grupos grandes." },
  { id: "chk-rain-jacket", grupo: "lluvia", texto: "Llevar chubasquero ligero y funda impermeable para mochilas." },
  { id: "chk-extra-shoes", grupo: "lluvia", texto: "Meter calcetines y calzado de repuesto para niños/as." },
  { id: "chk-powerbank", grupo: "tecnico", texto: "Powerbank cargada para mapas, tickets y chat del grupo." },
  { id: "chk-offline", grupo: "tecnico", texto: "Guardar capturas de tickets y plan por si falla internet." },
  { id: "chk-medical", grupo: "seguridad", texto: "Pequeño botiquín y medicación esencial para el grupo." },
  { id: "chk-emergency", grupo: "seguridad", texto: "Compartir números de emergencia y ubicación del alojamiento." }
];

window.CATEGORIES = [
  "hotel",
  "museo",
  "paseo",
  "mirador",
  "ciencia",
  "street art",
  "mercado",
  "parque",
  "experiencia",
  "zoo",
  "barco",
  "transporte",
  "historia"
];
